# Generated by Django 4.1.7 on 2023-11-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStand',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
    ]
