# Generated by Django 4.1.7 on 2023-11-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='reachable',
            field=models.CharField(max_length=255),
        ),
    ]
