# Generated by Django 4.1.7 on 2023-11-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_routes_reachable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_code', models.IntegerField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=255)),
            ],
        ),
    ]
