# Generated by Django 4.1.7 on 2023-11-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('C_id', models.IntegerField(primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('working_shift', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('D_id', models.IntegerField(primary_key=True, serialize=False)),
                ('D_name', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('working_shift', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Bus_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_no', to='routes.bus')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src', to='routes.busstand')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='routes.busstand')),
            ],
        ),
    ]
