# Generated by Django 4.1.7 on 2023-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_conductor_driver_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_stands_covered', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
