# Generated by Django 4.1.7 on 2023-11-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_fare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fare',
        ),
    ]
