# Generated by Django 4.1.7 on 2023-11-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_delete_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('Number_of_Stands_covered', models.IntegerField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
